plugins {
    id 'java-library'
    id 'maven-publish'
    id 'checkstyle'
    id 'jacoco'
    alias libs.plugins.yumi.gradle.licenser.plugin
    alias libs.plugins.jaredsburrows.license.plugin
}

java {
    withJavadocJar()
    withSourcesJar()
}

dependencies {
    api project(":static-analysis")
    implementation 'org.soot-oss:sootup.core:3.0.1'
    implementation 'org.soot-oss:sootup.java.core:3.0.1'
    implementation 'org.soot-oss:sootup.java.bytecode.frontend:3.0.1'
    implementation 'org.soot-oss:sootup.callgraph:3.0.1'

    testImplementation libs.assertj
    testImplementation libs.logback.classic
    testImplementation libs.commons.io
    testImplementation libs.lombok
    testImplementation libs.jooq
    testImplementation project(":assertions")
    testImplementation project(":builder")
    testImplementation project(":access")
    testImplementation project(":types")
    testImplementation project(":jooq-integration")
    testImplementation project(":type-utils")
    testImplementation project(":test-shared-impl")
    testAnnotationProcessor libs.lombok
}
