package tests.mirror.nondomainfilter;

import tests.mirror.nondomainbase.CodegenBase;

/**
 * Generated by some other code generator, recognizable by its superclass.
 */
public class CustomGeneratedClass extends CodegenBase {
}
