package tests.mirror.nondomainfilter;

/**
 * Generated by some other code generator, recognizable by an interface of its superclass.
 */
public class CustomGeneratedViaInterface extends IntermediateBase {
}
