plugins {
    id 'java-library'
    id 'maven-publish'
    id 'checkstyle'
    id 'jacoco'
    alias libs.plugins.yumi.gradle.licenser.plugin
    alias libs.plugins.jaredsburrows.license.plugin
}

java {
    withJavadocJar()
    withSourcesJar()
}

dependencies {
    api libs.slf4j.api
    api project(":mirror")
}
