plugins {
    id 'java-library'
    id 'maven-publish'
    id 'checkstyle'
    id 'jacoco'
    alias libs.plugins.yumi.gradle.licenser.plugin
    alias libs.plugins.jaredsburrows.license.plugin
}

java {
    withJavadocJar()
    withSourcesJar()
}

dependencies {
    api libs.slf4j.api
    api project(":static-analysis")
    implementation libs.jackson2.core
    implementation libs.jackson2.databind

    testImplementation libs.assertj
    testImplementation libs.logback.classic
    testImplementation project(":assertions")
    testImplementation project(":builder")
    testImplementation project(":access")
    testImplementation project(":type-utils")
    testImplementation project(":test-shared-impl")
    testAnnotationProcessor libs.lombok
}

test {
    finalizedBy jacocoTestReport
}
jacocoTestReport {
    dependsOn test
}

jacocoTestCoverageVerification.dependsOn jacocoTestReport
