/*
 *     ___
 *     │   ╲                 _
 *     │    ╲ ___ _ __  __ _(_)_ _
 *     |     ╲ _ ╲ '  ╲╱ _` │ │ ' ╲
 *     |_____╱___╱_│_│_╲__,_│_│_||_|
 *     │ │  (_)╱ _│___ __ _  _ __│ |___ ___
 *     │ │__│ │  _╱ -_) _│ ││ ╱ _│ ╱ -_|_-<
 *     │____│_│_│ ╲___╲__│╲_, ╲__│_╲___╱__╱
 *                      |__╱
 *
 *  Copyright 2019-2025 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.domainlifecycles.plugin.mirror;

import io.domainlifecycles.plugin.extensions.SerializationConfigurationExtension;
import io.domainlifecycles.plugins.mirror.MirrorSerializer;
import io.domainlifecycles.plugins.mirror.MirrorSerializerImpl;
import io.domainlifecycles.plugins.util.FileIOUtils;
import io.domainlifecycles.utils.ClassLoaderUtils;
import org.gradle.api.DefaultTask;
import org.gradle.api.NamedDomainObjectContainer;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.tasks.Classpath;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.Nested;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;

/**
 * An abstract Gradle task for rendering domain models as JSON files.
 *
 * This task processes serialization configurations and generates corresponding
 * JSON outputs for the specified bounded context packages. It utilizes a JSON
 * serializer implementation to convert the domain models into serialized JSON strings.
 *
 * The task includes functionality to dynamically add classpath files to the project
 * during execution and manages the generation of JSON files in the specified output directory.
 *
 * @author Leon Völlinger
 */
@DisableCachingByDefault(because = "Outputs depend on external environment and are not safely reproducible yet.")
public abstract class MirrorSerializerTask extends DefaultTask {

    private final static Logger log = LoggerFactory.getLogger(MirrorSerializerTask.class);

    /**
     * Retrieves the output directory for generated files.
     *
     * This method provides access to a {@code DirectoryProperty} that specifies
     * the directory where output files will be generated by the task.
     * When nothing is specified here, the default directory will be: {@code src/main/resources/META-INF/dlc}
     *
     * @return a {@code DirectoryProperty} representing the output directory for generated files.
     */
    @OutputDirectory
    @Optional
    public abstract DirectoryProperty getFileOutputDir();

    /**
     * Retrieves the serializations configuration container for the task.
     *
     * This method provides access to a container of {@code SerializationConfigurationExtension} objects,
     * which represent configuration settings for defining how domain models are serialized during task execution.
     * The container can be used to add, access, or modify serialization configurations dynamically.
     *
     * @return a {@code NamedDomainObjectContainer} of {@code SerializationConfigurationExtension}
     * providing configuration settings for serialization tasks.
     */
    @Nested
    public abstract NamedDomainObjectContainer<SerializationConfigurationExtension> getSerializations();

    private final ConfigurableFileCollection classesDirs = getProject().getObjects().fileCollection();
    private final ConfigurableFileCollection classpath = getProject().getObjects().fileCollection();

    /**
     * Retrieves the collection of directories containing the compiled class files.
     *
     * This method is annotated with `@InputFiles`, indicating that the returned
     * file collection is treated as input for Gradle's incremental build mechanism.
     * The classes directories are typically used as an input for analyzing or
     * processing compiled class files within the task.
     *
     * @return a `ConfigurableFileCollection` representing the directories of compiled class files.
     */
    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public ConfigurableFileCollection getClassesDirs() {
        return classesDirs;
    }

    /**
     * Retrieves the collection of files that form the classpath for this task.
     *
     * This method is annotated with `@InputFiles`, which indicates that the returned
     * file collection is treated as input for Gradle's incremental build mechanism.
     * The classpath typically includes dependencies and other resources required for
     * executing or generating output in the context of this task.
     *
     * @return a `ConfigurableFileCollection` representing the files that constitute
     *         the classpath for this task.
     */
    @Classpath
    public ConfigurableFileCollection getClasspath() {
        return classpath;
    }



    private MirrorSerializer mirrorSerializer;

    /**
     * Executes the task action for rendering domain models as JSON files.
     *
     * This method performs the following operations during execution:
     * - Initializes a JSON serializer with the configuration for pretty print.
     * - Dynamically adds the parent classpath files of the project to the current classpath.
     * - Iterates over the defined serialization configurations and processes each one
     *   by rendering the associated domain model as a JSON file and saving it to the output directory.
     *
     * The method relies on helper utilities and serializer implementations to perform
     * the necessary transformations and file operations.
     */
    @TaskAction
    public void action() {
        mirrorSerializer = new MirrorSerializerImpl(true);
        getSerializations().forEach(this::renderAndSaveModelAsJson);
    }

    private void renderAndSaveModelAsJson(final SerializationConfigurationExtension serializationConfigurationExtension) {
        var urls = ClassLoaderUtils.getClasspathFiles(this.getClasspath(), this.getClassesDirs());
        String jsonContent = mirrorSerializer.serialize(urls, serializationConfigurationExtension.getDomainModelPackages().getOrNull());
        Path filePath = getFileOutputDir()
            .file(serializationConfigurationExtension.getFileName().get())
            .get()
            .getAsFile()
            .toPath();

        log.info("Saving JSON model to {}", filePath);
        FileIOUtils.writeFileTo(filePath, jsonContent);
    }
}
