/*
 *     ___
 *     │   ╲                 _
 *     │    ╲ ___ _ __  __ _(_)_ _
 *     |     ╲ _ ╲ '  ╲╱ _` │ │ ' ╲
 *     |_____╱___╱_│_│_╲__,_│_│_||_|
 *     │ │  (_)╱ _│___ __ _  _ __│ |___ ___
 *     │ │__│ │  _╱ -_) _│ ││ ╱ _│ ╱ -_|_-<
 *     │____│_│_│ ╲___╲__│╲_, ╲__│_╲___╱__╱
 *                      |__╱
 *
 *  Copyright 2019-2024 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.domainlifecycles.plugins.viewer;

import java.net.URL;
import java.util.List;

/**
 * The DomainModelUploader interface defines a contract for components that facilitate
 * the process of uploading a serialized domain model to a designated Diagram Viewer system.
 *
 * This interface requires the implementation of a method to handle the uploading process
 * by initializing the domain model from the given classpath, optionally running a static
 * analysis of the domain classes on top of it, and providing the necessary configuration
 * parameters and communication details for the target system.
 *
 * Responsibilities:
 * - Initialize and serialize the domain model, and optionally run a static analysis of the
 *   domain classes and serialize its result.
 * - Ensure the delivery of the domain model (and, if analyzed, the static analysis result) to the
 *   Diagram Viewer through an HTTP-based API.
 * - Manage authentication and project-specific configurations during the upload.
 *
 * @author Leon Völlinger
 */
public interface DomainModelUploader {

    /**
     * Uploads a domain model, initialized from the given classpath, to a specific project in the
     * Diagram Viewer platform.
     *
     * This method initializes the domain model, optionally runs a static analysis of the domain
     * classes on top of it - so the Diagram Viewer can offer flow based diagram filtering - and
     * uploads both together with the configuration details required for proper association with
     * the target project on the Diagram Viewer.
     *
     * The method prepares and sends the required HTTP request, including authentication and
     * project-specific headers, and handles any potential errors during the upload process.
     *
     * @param classPathFiles        the classpath the domain model (and, if run, the static analysis)
     *                              is initialized from
     * @param domainModelPackages   a list of package names defining the domain model classes for processing
     * @param runStaticAnalysis     whether a static analysis of the domain classes should be run and its
     *                              result ({@code DomainCalls}) uploaded alongside the domain model
     * @param apiKey                the API key required for authentication with the Diagram Viewer platform
     * @param projectName           the name of the target project on the Diagram Viewer platform
     * @param diagramViewerBaseUrl  the base URL of the Diagram Viewer instance where the domain model should be uploaded
     */
    void uploadDomainModel(List<URL> classPathFiles, List<String> domainModelPackages, boolean runStaticAnalysis,
                           String apiKey, String projectName, String diagramViewerBaseUrl);

    /**
     * Same as {@link #uploadDomainModel(List, List, boolean, String, String, String)}, but streams the
     * request body to the Diagram Viewer as it is produced, instead of first assembling it completely
     * in memory as a JSON string and only then gzip-compressing and sending it as a whole.
     * <p>
     * For a domain of a few hundred types, the combined domain model and static analysis JSON can
     * already reach the tens of megabytes; building that up as a String (and then again as a
     * compressed byte array) before sending anything means holding several large, mostly redundant
     * copies of it in memory at once. This method instead pipes the JSON - as it is generated by the
     * underlying serializers, gzip-compressed on the fly - directly into the HTTP request body, so at
     * no point does the complete request body have to exist in memory as a single object. Since the
     * compressed size is not known upfront, the request is sent with a chunked transfer encoding
     * rather than a fixed {@code Content-Length}.
     * <p>
     * This is opt-in rather than the default: it trades a lower, flatter memory footprint for the
     * added complexity of a background thread producing the body while the request is in flight, and
     * for very large domains it is the difference between comfortably fitting into a build's memory
     * budget and risking an {@code OutOfMemoryError}. For smaller domains, the plain
     * {@link #uploadDomainModel(List, List, boolean, String, String, String)} is simpler and
     * sufficiently efficient.
     *
     * @param classPathFiles        the classpath the domain model (and, if run, the static analysis)
     *                              is initialized from
     * @param domainModelPackages   a list of package names defining the domain model classes for processing
     * @param runStaticAnalysis     whether a static analysis of the domain classes should be run and its
     *                              result ({@code DomainCalls}) uploaded alongside the domain model
     * @param apiKey                the API key required for authentication with the Diagram Viewer platform
     * @param projectName           the name of the target project on the Diagram Viewer platform
     * @param diagramViewerBaseUrl  the base URL of the Diagram Viewer instance where the domain model should be uploaded
     */
    void uploadDomainModelStreaming(List<URL> classPathFiles, List<String> domainModelPackages, boolean runStaticAnalysis,
                                    String apiKey, String projectName, String diagramViewerBaseUrl);
}
