CREATE SCHEMA TEST_DOMAIN;

CREATE SEQUENCE TEST_DOMAIN.TEST_ROOT_SIMPLE_ID_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1111 CACHE 20;

CREATE TABLE TEST_DOMAIN.TEST_ROOT_SIMPLE
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    NAME                VARCHAR2(200)
);

CREATE TABLE TEST_DOMAIN.TEST_ROOT_SIMPLE_UUID
(
    ID                  VARCHAR2(36) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    NAME                VARCHAR2(200)
);

/*
   1 BESTELLUNG hat 1-n BESTELLPOSITIONEN
   1 BESTELLUNG hat genau 1 BESTELLSTATUS
   1 BESTELLUNG hat 0-n KOMMENTARE
   1 BESTELLUNG muss genau 1 LIEFERADRESSE besitzen
   1 BESTELLUNG kann mehrere AKTIONSCODES (Value Object) zugeordnet haben
   Es wird pro BESTELLUNG nur maximal 1 POSITION pro ARTIKEL erlaubt, d.h.
   es darf keine 2 POSITIONEN in einer BESTELLUNG geben, bei welcher der gleiche ARTIKEL gewählt wurde

   Der ARTIKEL aus einer BESTELLPOSITION verweist auf ein anderes AGGREGATEROOT

   Der KUNDE mit KUNDENNUMMER ist Teil eines anderen BOUNDED CONTEXT
 */

CREATE SEQUENCE TEST_DOMAIN.LIEFERADRESSE_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.LIEFERADRESSE_BV3
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    NAME                VARCHAR2(200) NOT NULL,
    STRASSE             VARCHAR2(200) NOT NULL,
    POSTLEITZAHL        VARCHAR2(10) NOT NULL,
    ORT                 VARCHAR2(200) NOT NULL
);

CREATE SEQUENCE TEST_DOMAIN.BESTELLUNG_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.BESTELLUNG_BV3
(
    ID                    NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION   NUMBER(18) NOT NULL,
    PRIORITAET            NUMBER(1) NOT NULL,
    KUNDEN_NUMMER         VARCHAR2(20) NOT NULL,
    GESAMT_PREIS_BETRAG   NUMBER(10,2) NOT NULL,
    GESAMT_PREIS_WAEHRUNG VARCHAR2(3) NOT NULL,
    LIEFERADRESSE_ID      NUMBER(18) NOT NULL,
    FOREIGN KEY (LIEFERADRESSE_ID) REFERENCES TEST_DOMAIN.LIEFERADRESSE_BV3 (ID)
);

CREATE TABLE TEST_DOMAIN.AKTIONS_CODE_BV3
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.BESTELLUNG_BV3 (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AKTIONS_CODE_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE SEQUENCE TEST_DOMAIN.BESTELL_POSITION_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.BESTELL_POSITION_BV3
(
    ID                   NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION  NUMBER(18) NOT NULL,
    BESTELLUNG_ID        NUMBER(18) NOT NULL,
    ARTIKEL_ID           NUMBER(18) NOT NULL,
    STUECKZAHL           NUMBER(10) NOT NULL,
    STUECKPREIS_BETRAG   NUMBER(10,2) NOT NULL,
    STUECKPREIS_WAEHRUNG VARCHAR2(3) NOT NULL,
    FOREIGN KEY (BESTELLUNG_ID) REFERENCES TEST_DOMAIN.BESTELLUNG_BV3 (ID)
);

CREATE UNIQUE INDEX TEST_DOMAIN.BESTELLUNG_ARTIKEL_BV3_UNIQUE ON TEST_DOMAIN.BESTELL_POSITION_BV3 (BESTELLUNG_ID, ARTIKEL_ID);

CREATE SEQUENCE TEST_DOMAIN.BESTELL_STATUS_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.BESTELL_STATUS_BV3
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    BESTELLUNG_ID       NUMBER(18) NOT NULL,
    STATUS_CODE         VARCHAR2(20),
    STATUS_AENDERUNG_AM TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FOREIGN KEY (BESTELLUNG_ID) REFERENCES TEST_DOMAIN.BESTELLUNG_BV3 (ID)
);

CREATE SEQUENCE TEST_DOMAIN.BESTELL_KOMMENTAR_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.BESTELL_KOMMENTAR_BV3
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    BESTELLUNG_ID       NUMBER(18) NOT NULL,
    KOMMENTAR_AM        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    KOMMENTAR_TEXT      VARCHAR2(1000),
    FOREIGN KEY (BESTELLUNG_ID) REFERENCES TEST_DOMAIN.BESTELLUNG_BV3 (ID)
);


/*
Auto Mapping Value Objects case
*/

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT
(
    ID                          NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION         NUMBER(18) NOT NULL,
    TEXT                        VARCHAR2(20) NULL,
    MY_SIMPLE_VO_VALUE          VARCHAR2(20) NOT NULL,
    MY_COMPLEX_VO_VALUE_A       VARCHAR2(20) NULL,
    MY_COMPLEX_VO_VALUE_B_VALUE VARCHAR2(20) NULL,
    VO_IDENTITY_REF_VALUE       VARCHAR2(20) NULL,
    VO_IDENTITY_REF_ID_REF      NUMBER(18) NULL
);

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY
(
    ID                          NUMBER(18) PRIMARY KEY,
    ROOT_ID                     NUMBER(18) NOT NULL,
    CONCURRENCY_VERSION         NUMBER(18) NOT NULL,
    TEXT                        VARCHAR2(20) NULL,
    MY_COMPLEX_VO_VALUE_A       VARCHAR2(20) NULL,
    MY_COMPLEX_VO_VALUE_B_VALUE VARCHAR2(20) NULL,
    FOREIGN KEY (ROOT_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2_ONE_TO_MANY3_SET_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2_ONE_TO_MANY3_SET
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2 (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY_ONE_TO_MANY_SET_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY_ONE_TO_MANY_SET
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY (ID)
);

/*
 Optional Case
 */
CREATE TABLE TEST_DOMAIN.REF_AGG
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    MANDATORY_TEXT      VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT       VARCHAR2(20) NULL
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_ENTITY_ID_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.OPTIONAL_ENTITY
(
    ID                                                                 NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION                                                NUMBER(18) NOT NULL,
    MANDATORY_TEXT                                                     VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT                                                      VARCHAR2(20) NULL,
    MANDATORY_SIMPLE_VALUE_OBJECT_VALUE                                VARCHAR2(20) NOT NULL,
    OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE                                 VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                      VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                       VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                       NUMBER(18) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                       VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                        VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE   VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                        NUMBER(18) NULL
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_AGGREGATE_ID_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.OPTIONAL_AGGREGATE
(
    ID                                                                 NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION                                                NUMBER(18) NOT NULL,
    MANDATORY_TEXT                                                     VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT                                                      VARCHAR2(20) NULL,
    OPTIONAL_LONG                                                      NUMBER(18) NULL,
    MANDATORY_SIMPLE_VALUE_OBJECT_VALUE                                VARCHAR2(20) NOT NULL,
    OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE                                 VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                      VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                       VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                       NUMBER(18) NULL,
    OPTIONAL_ENTITY_ID                                                 NUMBER(18) NULL,
    OPTIONAL_REF_ID                                                    NUMBER(18) NULL,
    REF_VALUE_OBJECT_MANDATORY_TEXT                                    VARCHAR2(20) NOT NULL,
    REF_VALUE_OBJECT_OPTIONAL_REF                                      NUMBER(18) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                       VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                        VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE   VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                        NUMBER(18) NULL,
    FOREIGN KEY (OPTIONAL_ENTITY_ID) REFERENCES TEST_DOMAIN.OPTIONAL_ENTITY (ID),
    FOREIGN KEY (OPTIONAL_REF_ID) REFERENCES TEST_DOMAIN.REF_AGG (ID),
    FOREIGN KEY (REF_VALUE_OBJECT_OPTIONAL_REF) REFERENCES TEST_DOMAIN.REF_AGG (ID)
);

CREATE TABLE TEST_DOMAIN.OPTIONAL_ENTITY_COMPLEX_VALUE_OBJECT_LIST
(
    ID                                  NUMBER(18) PRIMARY KEY,
    CONTAINER_ID                        NUMBER(18) NOT NULL,
    MANDATORY_TEXT                      VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT                       VARCHAR2(20) NULL,
    MANDATORY_SIMPLE_VALUE_OBJECT_VALUE VARCHAR2(20) NOT NULL,
    OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    OPTIONAL_LONG                       NUMBER(18) NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.OPTIONAL_ENTITY (ID)
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_ENTITY_COMPLEX_VALUE_OBJECT_LIST_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.OPTIONAL_AGGREGATE_REF_VALUE_OBJECT_LIST
(
    ID             NUMBER(18) PRIMARY KEY,
    CONTAINER_ID   NUMBER(18) NOT NULL,
    MANDATORY_TEXT VARCHAR2(20) NOT NULL,
    OPTIONAL_REF   NUMBER(18) NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.OPTIONAL_AGGREGATE (ID),
    FOREIGN KEY (OPTIONAL_REF) REFERENCES TEST_DOMAIN.REF_AGG (ID)
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_AGGREGATE_REF_VALUE_OBJECT_LIST_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.VALIDATED_AGGREGATE_ROOT
(
    ID                  NUMBER(18) PRIMARY KEY,
    TEXT                VARCHAR2(100) NOT NULL,
    OPTIONAL_TEXT       VARCHAR2(10),
    CONCURRENCY_VERSION NUMBER(18) NOT NULL
);
