CREATE SCHEMA TEST_DOMAIN;

CREATE SEQUENCE TEST_DOMAIN.TEST_ROOT_SIMPLE_ID_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1111 CACHE 20;

CREATE TABLE TEST_DOMAIN.TEST_ROOT_SIMPLE
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    NAME                VARCHAR2(200)
);

CREATE TABLE TEST_DOMAIN.TEST_ROOT_SIMPLE_UUID
(
    ID                  VARCHAR2(36) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    NAME                VARCHAR2(200)
);

/*
   1 ORDER has 1-n ORDER_ITEMS
   1 ORDER has exactly 1 ORDER_STATUS
   1 ORDER has 0-n COMMENTS
   1 ORDER must have exactly 1 DELIVERY_ADDRESS
   1 ORDER can have several PROMO_CODES (Value Object) assigned

   Only a maximum of 1 ITEM per ARTICLE is allowed per ORDER, i.e.
   there must not be 2 ITEMS in an ORDER referencing the same ARTICLE

   The ARTICLE referenced by an ORDER_ITEM points to another AGGREGATEROOT

   The CUSTOMER identified by CUSTOMER_NUMBER is part of another BOUNDED CONTEXT
 */

CREATE SEQUENCE TEST_DOMAIN.DELIVERY_ADDRESS_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.DELIVERY_ADDRESS_BV3
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    NAME                VARCHAR2(200) NOT NULL,
    STREET              VARCHAR2(200) NOT NULL,
    POSTAL_CODE         VARCHAR2(10) NOT NULL,
    CITY                VARCHAR2(200) NOT NULL
);

CREATE SEQUENCE TEST_DOMAIN.ORDER_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.ORDER_BV3
(
    ID                    NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION   NUMBER(18) NOT NULL,
    PRIORITY              NUMBER(1) NOT NULL,
    CUSTOMER_NUMBER       VARCHAR2(20) NOT NULL,
    TOTAL_PRICE_AMOUNT    NUMBER(10,2) NOT NULL,
    TOTAL_PRICE_CURRENCY  VARCHAR2(3) NOT NULL,
    DELIVERY_ADDRESS_ID   NUMBER(18) NOT NULL,
    FOREIGN KEY (DELIVERY_ADDRESS_ID) REFERENCES TEST_DOMAIN.DELIVERY_ADDRESS_BV3 (ID)
);

CREATE TABLE TEST_DOMAIN.PROMO_CODE_BV3
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.ORDER_BV3 (ID)
);

CREATE SEQUENCE TEST_DOMAIN.PROMO_CODE_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE SEQUENCE TEST_DOMAIN.ORDER_ITEM_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.ORDER_ITEM_BV3
(
    ID                    NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION   NUMBER(18) NOT NULL,
    ORDER_ID              NUMBER(18) NOT NULL,
    ARTICLE_ID            NUMBER(18) NOT NULL,
    QUANTITY              NUMBER(10) NOT NULL,
    UNIT_PRICE_AMOUNT     NUMBER(10,2) NOT NULL,
    UNIT_PRICE_CURRENCY   VARCHAR2(3) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES TEST_DOMAIN.ORDER_BV3 (ID)
);

CREATE UNIQUE INDEX TEST_DOMAIN.ORDER_ARTICLE_BV3_UNIQUE ON TEST_DOMAIN.ORDER_ITEM_BV3 (ORDER_ID, ARTICLE_ID);

CREATE SEQUENCE TEST_DOMAIN.ORDER_STATUS_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.ORDER_STATUS_BV3
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    ORDER_ID            NUMBER(18) NOT NULL,
    STATUS_CODE         VARCHAR2(20),
    STATUS_CHANGED_AT   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES TEST_DOMAIN.ORDER_BV3 (ID)
);

CREATE SEQUENCE TEST_DOMAIN.ORDER_COMMENT_ID_BV3_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.ORDER_COMMENT_BV3
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    ORDER_ID            NUMBER(18) NOT NULL,
    COMMENTED_AT        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COMMENT_TEXT        VARCHAR2(1000),
    FOREIGN KEY (ORDER_ID) REFERENCES TEST_DOMAIN.ORDER_BV3 (ID)
);

/*
Auto Mapping Value Objects case
*/

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT
(
    ID                          NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION         NUMBER(18) NOT NULL,
    TEXT                        VARCHAR2(20) NULL,
    MY_SIMPLE_VO_VALUE          VARCHAR2(20) NOT NULL,
    MY_COMPLEX_VO_VALUE_A       VARCHAR2(20) NULL,
    MY_COMPLEX_VO_VALUE_B_VALUE VARCHAR2(20) NULL,
    VO_IDENTITY_REF_VALUE       VARCHAR2(20) NULL,
    VO_IDENTITY_REF_ID_REF      NUMBER(18) NULL
);

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY
(
    ID                          NUMBER(18) PRIMARY KEY,
    ROOT_ID                     NUMBER(18) NOT NULL,
    CONCURRENCY_VERSION         NUMBER(18) NOT NULL,
    TEXT                        VARCHAR2(20) NULL,
    MY_COMPLEX_VO_VALUE_A       VARCHAR2(20) NULL,
    MY_COMPLEX_VO_VALUE_B_VALUE VARCHAR2(20) NULL,
    FOREIGN KEY (ROOT_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2_ONE_TO_MANY3_SET_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2_ONE_TO_MANY3_SET
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_AGGREGATE_ROOT_VALUE_OBJECTS_ONE_TO_MANY2 (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY (ID)
);

CREATE SEQUENCE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY_ONE_TO_MANY_SET_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY_ONE_TO_MANY_SET
(
    ID           NUMBER(18) PRIMARY KEY,
    CONTAINER_ID NUMBER(18) NOT NULL,
    VALUE        VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.AUTO_MAPPED_VO_ENTITY_VALUE_OBJECTS_ONE_TO_MANY (ID)
);

/*
 Optional Case
 */
CREATE TABLE TEST_DOMAIN.REF_AGG
(
    ID                  NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION NUMBER(18) NOT NULL,
    MANDATORY_TEXT      VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT       VARCHAR2(20) NULL
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_ENTITY_ID_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.OPTIONAL_ENTITY
(
    ID                                                                 NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION                                                NUMBER(18) NOT NULL,
    MANDATORY_TEXT                                                     VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT                                                      VARCHAR2(20) NULL,
    MANDATORY_SIMPLE_VALUE_OBJECT_VALUE                                VARCHAR2(20) NOT NULL,
    OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE                                 VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                      VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                       VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                       NUMBER(18) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                       VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                        VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE   VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                        NUMBER(18) NULL
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_AGGREGATE_ID_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.OPTIONAL_AGGREGATE
(
    ID                                                                 NUMBER(18) PRIMARY KEY,
    CONCURRENCY_VERSION                                                NUMBER(18) NOT NULL,
    MANDATORY_TEXT                                                     VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT                                                      VARCHAR2(20) NULL,
    OPTIONAL_LONG                                                      NUMBER(18) NULL,
    MANDATORY_SIMPLE_VALUE_OBJECT_VALUE                                VARCHAR2(20) NOT NULL,
    OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE                                 VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                      VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                       VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE VARCHAR2(20) NOT NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    MANDATORY_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                       NUMBER(18) NULL,
    OPTIONAL_ENTITY_ID                                                 NUMBER(18) NULL,
    OPTIONAL_REF_ID                                                    NUMBER(18) NULL,
    REF_VALUE_OBJECT_MANDATORY_TEXT                                    VARCHAR2(20) NOT NULL,
    REF_VALUE_OBJECT_OPTIONAL_REF                                      NUMBER(18) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_TEXT                       VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_TEXT                        VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_MANDATORY_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE   VARCHAR2(20) NULL,
    OPTIONAL_COMPLEX_VALUE_OBJECT_OPTIONAL_LONG                        NUMBER(18) NULL,
    FOREIGN KEY (OPTIONAL_ENTITY_ID) REFERENCES TEST_DOMAIN.OPTIONAL_ENTITY (ID),
    FOREIGN KEY (OPTIONAL_REF_ID) REFERENCES TEST_DOMAIN.REF_AGG (ID),
    FOREIGN KEY (REF_VALUE_OBJECT_OPTIONAL_REF) REFERENCES TEST_DOMAIN.REF_AGG (ID)
);

CREATE TABLE TEST_DOMAIN.OPTIONAL_ENTITY_COMPLEX_VALUE_OBJECT_LIST
(
    ID                                  NUMBER(18) PRIMARY KEY,
    CONTAINER_ID                        NUMBER(18) NOT NULL,
    MANDATORY_TEXT                      VARCHAR2(20) NOT NULL,
    OPTIONAL_TEXT                       VARCHAR2(20) NULL,
    MANDATORY_SIMPLE_VALUE_OBJECT_VALUE VARCHAR2(20) NOT NULL,
    OPTIONAL_SIMPLE_VALUE_OBJECT_VALUE  VARCHAR2(20) NULL,
    OPTIONAL_LONG                       NUMBER(18) NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.OPTIONAL_ENTITY (ID)
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_ENTITY_COMPLEX_VALUE_OBJECT_LIST_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.OPTIONAL_AGGREGATE_REF_VALUE_OBJECT_LIST
(
    ID             NUMBER(18) PRIMARY KEY,
    CONTAINER_ID   NUMBER(18) NOT NULL,
    MANDATORY_TEXT VARCHAR2(20) NOT NULL,
    OPTIONAL_REF   NUMBER(18) NULL,
    FOREIGN KEY (CONTAINER_ID) REFERENCES TEST_DOMAIN.OPTIONAL_AGGREGATE (ID),
    FOREIGN KEY (OPTIONAL_REF) REFERENCES TEST_DOMAIN.REF_AGG (ID)
);

CREATE SEQUENCE TEST_DOMAIN.OPTIONAL_AGGREGATE_REF_VALUE_OBJECT_LIST_SEQ MINVALUE 1000 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20;

CREATE TABLE TEST_DOMAIN.VALIDATED_AGGREGATE_ROOT
(
    ID                  NUMBER(18) PRIMARY KEY,
    TEXT                VARCHAR2(100) NOT NULL,
    OPTIONAL_TEXT       VARCHAR2(10),
    CONCURRENCY_VERSION NUMBER(18) NOT NULL
);
